### ISSUE TITLE
Revisar página inicial e de filmes em exibição

### ISSUE THREAD

**Issue by anvitrola** [leo-tavares/resiliaflix-v2.0#1]
- Deve conter informações sobre o serviço;
- Deve conter o banner de 12 filmes;
- Onclick no banner, o usuário deve ser redirecionado para um modal de informações;

PS.: Quem for editar o arquivo, coloca na nav-bar o input para pesquisa e tenta fazer os carroséis funcionarem!

**Comment by leo-tavares** [comment]
Oi @anvitrola eu abrir um draft (https://github.com/leo-tavares/resiliaflix-v2.0/pull/2), vou fazer a revisão por lá e em seguida linkar aqui nessa issue ok?

**Comment by anvitrola** [comment]
A única coisa que falta na página de filmes em exibição é retirar o "Entrar" do cabeçalho, visto que o usuário já estará logado na plataforma. @leo-tavares
