### ISSUE TITLE
Página de contato

### ISSUE THREAD

**Issue by anvitrola** [leo-tavares/resiliaflix-v2.0#4]
Inspirados no exemplo abaixo, podemos fazer um container e dentro dele colocar os cards dessa forma, com nome, foto, cidade e na foto talvez possa haver um link para o linkedin da pessoa ou podemos colocar o linkedin embaixo mesmo. 

![pagContato](https://user-images.githubusercontent.com/62806299/107686346-df6e5e80-6c83-11eb-9ea2-1e06c6efaa45.png)

**Comment by leo-tavares** [comment]
Oi @GilbertoPereira1, encontrei esse link da doc do bootstrap => https://getbootstrap.com/docs/4.3/components/card/ . Acho que vai te ajudar

**Comment by ghost** [comment]
@anvitrola terminei a pagina de contato, falta apenas a foto da rebeca e do felipe, depois veja se o layout esta ok

**Comment by anvitrola** [comment]
Ajeitei o bug no layout (o model estava vazando) e agora a página está responsiva. Finalizamos essa parte! :)
